### ISSUE TITLE
build is unsuccessful

### ISSUE THREAD

**Issue by amaendle** [chasemc/electricShine#343]
I'm using R-4.0.2 ond windows and cannot successfully build my shiny app using electricShine:

```
electricShine::electrify(app_name = "DrXplor",
                         short_description = "does something",
                         semantic_version = "1.0.0",
                         build_path = buildPath,
                         cran_like_url = "https://cran.r-project.org",
                         function_name = "run_app",
                         local_package_path = "U:/R/DrXpackage/drX_0.1.0.tar.gz",
                         run_build = T)
```

The log in the console seems fine to me until the electron app is to be built:

```
> electron-builder install-app-deps

  â€¢ electron-builder  version=22.8.0
  â€¢ loaded configuration  file=package.json ("build" field)
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.2 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN notsup Unsupported engine for watchpack-chokidar2@2.0.0: wanted: {"node":"<8.10.0"} (current: {"node":"12.16.2","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: watchpack-chokidar2@2.0.0
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules\watchpack-chokidar2\node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

added 1047 packages from 578 contributors and audited 1051 packages in 41.011s

57 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities


C:\Users\username.FI\AppData\Local\Temp\RtmpIZj0ud\DrXplor>0
Building your Electron app.
Microsoft Windows [Version 10.0.18362.959]
(c) 2019 Microsoft Corporation. Alle Rechte vorbehalten.

C:\Users\username.FI\AppData\Local\Temp\RtmpIZj0ud>cd "C:/Users/username.FI/AppData/Local/Temp/RtmpIZj0ud//DrXplor" && "C:/Users/username.FI/Documents/R/win-library/4.0/electricShine/nodejs/npm" run release --scripts-prepend-node-path

> DrXplor@1.0.0 release C:\Users\username.FI\AppData\Local\Temp\RtmpIZj0ud\DrXplor
> npm test && webpack --config=build/webpack.app.config.js --env=production && electron-builder


> DrXplor@1.0.0 test C:\Users\username.FI\AppData\Local\Temp\RtmpIZj0ud\DrXplor
> npm run unit && npm run e2e


> DrXplor@1.0.0 preunit C:\Users\username.FI\AppData\Local\Temp\RtmpIZj0ud\DrXplor
> webpack --config=build/webpack.unit.config.js --env=test --display=none

C:\Users\username.FI\AppData\Local\Temp\RtmpIZj0ud\DrXplor\node_modules\webpack-cli\bin\cli.js:93
				throw err;
				^

TypeError: merge is not a function
    at module.exports (C:\Users\username.FI\AppData\Local\Temp\RtmpIZj0ud\DrXplor\build\webpack.unit.config.js:22:10)
    at handleFunction (C:\Users\username.FI\AppData\Local\Temp\RtmpIZj0ud\DrXplor\node_modules\webpack-cli\bin\utils\prepareOptions.js:21:13)
    at prepareOptions (C:\Users\username.FI\AppData\Local\Temp\RtmpIZj0ud\DrXplor\node_modules\webpack-cli\bin\utils\prepareOptions.js:9:5)
    at requireConfig (C:\Users\username.FI\AppData\Local\Temp\RtmpIZj0ud\DrXplor\node_modules\webpack-cli\bin\utils\convert-argv.js:117:14)
    at C:\Users\username.FI\AppData\Local\Temp\RtmpIZj0ud\DrXplor\node_modules\webpack-cli\bin\utils\convert-argv.js:123:17
    at Array.forEach (<anonymous>)
    at module.exports (C:\Users\username.FI\AppData\Local\Temp\RtmpIZj0ud\DrXplor\node_modules\webpack-cli\bin\utils\convert-argv.js:121:15)
    at C:\Users\username.FI\AppData\Local\Temp\RtmpIZj0ud\DrXplor\node_modules\webpack-cli\bin\cli.js:71:45
    at Object.parse (C:\Users\username.FI\AppData\Local\Temp\RtmpIZj0ud\DrXplor\node_modules\webpack-cli\node_modules\yargs\yargs.js:576:18)
    at C:\Users\username.FI\AppData\Local\Temp\RtmpIZj0ud\DrXplor\node_modules\webpack-cli\bin\cli.js:49:8
    at Object.<anonymous> (C:\Users\username.FI\AppData\Local\Temp\RtmpIZj0ud\DrXplor\node_modules\webpack-cli\bin\cli.js:366:3)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1042:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (C:\Users\username.FI\AppData\Local\Temp\RtmpIZj0ud\DrXplor\node_modules\webpack\bin\webpack.js:156:2)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! DrXplor@1.0.0 preunit: `webpack --config=build/webpack.unit.config.js --env=test --display=none`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the DrXplor@1.0.0 preunit script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\username.FI\AppData\Roaming\npm-cache\_logs\2020-08-06T08_14_26_180Z-debug.log
npm ERR! Test failed.  See above for more details.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! DrXplor@1.0.0 release: `npm test && webpack --config=build/webpack.app.config.js --env=production && electron-builder`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the DrXplor@1.0.0 release script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\username.FI\AppData\Roaming\npm-cache\_logs\2020-08-06T08_14_26_204Z-debug.log
```

**Comment by chasemc** [comment]
Looks like the JS dependency `webpack-merge` had a breaking change not caught by the tests here. 
See link for more info:
https://github.com/survivejs/webpack-merge/blob/master/CHANGELOG.md#503--2020-07-06


I made updates in the `webpackmerge-fix` that should fix it, but I won't be able merge the fix until late next week. In the meantime you can try installing it by: 

`remotes::install_github("chasemc/electricShine@webpackmerge-fix")`

**Comment by bcrossman** [comment]
So this might be unrelated, but after using the new "webpackmerge-fix", the DemoApp successfully builds but after install it never moves past "Loading Application" screen.  I built the app on two different Window machines with the same result.  However could still be a "me" issue if it relates to particular package or setting issues that I have on both machines.  Let me know what additional troubleshooting / logging info would be helpful.

**Comment by chasemc** [comment]
Finishing my Dissertation edits in spare time. Trying to get to this after this weekend

**Comment by bcrossman** [comment]
> Finishing my Dissertation edits in spare time. Trying to get to this after this weekend

No worries at all.  Best of luck that the edits come quick and easy!
